## Numpy Basics
* Creating numpy arrays
* Numpy Arrays vs Python Lists
* arange vs linspace
* Basic array operations
* Indexing/Slicing/Iterating numpy Arrays

### Creating Arrays

#### Creating 1 and 2 dimensional arrays

In [29]:
import numpy as np

In [30]:
b = np.array([2,9,1,56])
b

array([ 2,  9,  1, 56])

In [31]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int64'), (4,), 1, 4)

In [32]:
c = np.array([[11.2, 22.2], [12, 44]])
c

array([[11.2, 22.2],
       [12. , 44. ]])

In [33]:
c.dtype, c.shape, c.ndim, c.size, c.itemsize

(dtype('float64'), (2, 2), 2, 4, 8)

In [34]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.dtype, a.shape, a.ndim, a.size, a.itemsize

(dtype('int64'), (3, 4), 2, 12, 8)

In [36]:
a = np.ones(6).reshape(3,2),
b = np.zeros(8).reshape(2,4),
c = np.random.rand(10).reshape(5,2),
a,b,c

((array([[1., 1.],
         [1., 1.],
         [1., 1.]]),), (array([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),), (array([[0.05442362, 0.52398429],
         [0.47600048, 0.0198957 ],
         [0.93041624, 0.94274199],
         [0.25520847, 0.86843788],
         [0.17866362, 0.14161482]]),))

#### Creating n dimenional arrays

In [37]:
# This will create a ndim array which will have 3 sub-arrays of shape(2,5)
a = np.random.randint(10, size=(3, 2, 5))
a

array([[[6, 4, 1, 4, 3],
        [5, 0, 6, 4, 9]],

       [[1, 5, 2, 1, 2],
        [9, 5, 0, 3, 0]],

       [[4, 8, 9, 5, 8],
        [7, 9, 7, 8, 9]]])

In [38]:
# This will create ndim array with 4 sub-arrays each having a 3 sub-sub-arrays of shape(3,2)
a = np.empty((3,4,3,2), dtype=int)
a, a.ndim, a.shape, a.size

(array([[[[     140118469729720,       94179392071024],
          [      94179367201872,                   10],
          [                  11,          -4244635901]],
 
         [[    -275968828700929,   -69235104739754240],
          [      -1060856986369,  2574352502877767984],
          [     140118342889072,       94179369472960]],
 
         [[-7368309629848930932,      140118390647280],
          [     140118347322096,  4855390706983928003],
          [     140118342889200,      140118342962400]],
 
         [[ 6699708544685076800,      140118436811440],
          [      94179369473120,   410024062354718713],
          [     140118472639408,       94179369349920]]],
 
 
        [[[ 5799929027325005261,      140118342889264],
          [      94179369475232,  7160701276206254457],
          [     140118342962512,      140118473895472]],
 
         [[ 6441946085325401749,      140118342962568],
          [     140118473895416,  5813800682530690364],
          [     14011844818280

In [39]:
a = np.fromfunction(lambda i, j: (i + j), (3, 2), dtype=int)
a

array([[0, 1],
       [1, 2],
       [2, 3]])

### arange vs linspace

In [40]:
# arnage(start, stop, step)
a = np.arange(10, 40, 5)
a

array([10, 15, 20, 25, 30, 35])

In [41]:
# linspace(start, stop, number) number is optional and default vlaue is 50
a = np.linspace(10, 40)
a

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [42]:
a = np.linspace(10, 40, 10)
a

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ])

## Iterating numpy arrays

In [43]:
a = np.arange(30).reshape(6,5)
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]


In [44]:
for cell in a.flat:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [45]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
for idx, val in np.ndenumerate(a):
    print(f"Index = {idx}, Value={val}")

Index = (0, 0), Value=0
Index = (0, 1), Value=1
Index = (0, 2), Value=2
Index = (0, 3), Value=3
Index = (0, 4), Value=4
Index = (1, 0), Value=5
Index = (1, 1), Value=6
Index = (1, 2), Value=7
Index = (1, 3), Value=8
Index = (1, 4), Value=9
Index = (2, 0), Value=10
Index = (2, 1), Value=11
Index = (2, 2), Value=12
Index = (2, 3), Value=13
Index = (2, 4), Value=14
Index = (3, 0), Value=15
Index = (3, 1), Value=16
Index = (3, 2), Value=17
Index = (3, 3), Value=18
Index = (3, 4), Value=19
Index = (4, 0), Value=20
Index = (4, 1), Value=21
Index = (4, 2), Value=22
Index = (4, 3), Value=23
Index = (4, 4), Value=24
Index = (5, 0), Value=25
Index = (5, 1), Value=26
Index = (5, 2), Value=27
Index = (5, 3), Value=28
Index = (5, 4), Value=29


## Operations on arrays

In [55]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
b = np.arange(10,16).reshape(3,2)
b

array([[10, 11],
       [12, 13],
       [14, 15]])

In [57]:
a + b

array([[10, 12],
       [14, 16],
       [18, 20]])

In [59]:
a * b

array([[ 0, 11],
       [24, 39],
       [56, 75]])

In [60]:
a - b

array([[-10, -10],
       [-10, -10],
       [-10, -10]])

In [64]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
a.sum(axis=0) # sum of all coulmns

array([30, 34, 38, 42, 46])

In [67]:
a.sum(axis=1) # sum of all rows

array([10, 35, 60, 85])

### Lists vs Numpy arrays

In [76]:
import random, sys

In [111]:
%%time
l = list(range(900000))

CPU times: user 13.2 ms, sys: 4.14 ms, total: 17.3 ms
Wall time: 17.1 ms


In [112]:
%%time
a = np.arange(900000)

CPU times: user 987 µs, sys: 3.73 ms, total: 4.71 ms
Wall time: 3.97 ms


In [113]:
sys.getsizeof(l)

8100112

In [114]:
sys.getsizeof(a)

7200096